<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<%@ page language="java" contentType="text/html; charset=windows-1252" pageEncoding="windows-1252"%>
<%@page import="com.google.appengine.api.users.UserServiceFactory"%>
<%@page import="com.google.appengine.api.users.User"%>
<%@page import="com.google.appengine.api.users.UserService"%>


<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>Delivery Pizza Cloud</title>
	<link rel="stylesheet" type="text/css" href="/form/view.css" media="all"/>
	<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.19.custom.css" media="all"/>

<style type="text/css">
.title {
	-moz-box-shadow:inset 0px 4px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 4px 0px 0px #ffffff;
	box-shadow:inset 0px 4px 0px 0px #ffffff;
	background-color:transparent;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	display:inline-block;
	color:#b04c4c;
	font-family:arial;
	font-size:22px;
	font-weight:bold;
	padding:9px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.title:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */

</style>


	<style type="text/css">
.fazerPedidoButton {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dba8a8;
	display:inline-block;
	color:#d14b4b;
	font-family:arial;
	font-size:21px;
	font-weight:bold;
	padding:23px 47px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.fazerPedidoButton:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.fazerPedidoButton:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */

</style>
	
	<script type="text/javascript" src="/form/view.js"></script>
	<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="/js/jquery.form.js"></script>
	<script type="text/javascript" src="/js/jquery-ui-1.8.19.custom.min.js"></script>
	
	
</head>
<body id="main_body" >
	
			
	<img id="top" src="/form/top.png" alt=""/>
		<div id="form_container" style="min-height: 550px; text-align: center; vertical-align: middle;">
				
			<div class="form_description" align="center" style="padding: 5px;">
				
				<span class="title">Bem Vindo ao Delivery Pizza Cloud!</span>
				
			</div>
			
			<a href="/form/form.jsp" class="fazerPedidoButton">Fazer Pedido</a>
			<br/><br/><br/><br/>
			<img src="/form/gae_pizza_delivery.png" alt="" />
			
			
		</div> 
</body>
</html>